title: "Building Websites in GitHub"
description: "This research project develops training materials for reseachers wanting to learn to build project
websites in GitHub with GitHub Pages."
email: "https://www.psychologie.uni-wuerzburg.de/expklin/personen/yu-fang-yang/"
twitter: "https://twitter.com/ufangyang"
